#!/usr/bin/env bash
set -euo pipefail
JPEG_BIN="${JPEG_BIN:-/home/lgryglicki/go/bin/jpeg}"
IRRATIO="${IRRATIO:-${IRT:-2.5}}"
IRS="${IRS:-1.0}"
IRL="${IRL:-1.0}"
IRSH="${IRSH:-0.08}"
IRGM="${IRGM:-1.0}"
IRSPLIT="${IRSPLIT:-${IRSSPLIT:-0.55}}"
IRSENDR="${IRSENDR:-0.0}"
IRSENDG="${IRSENDG:-1.0}"
IRSENDB="${IRSENDB:-0.0}"
IRLSPLIT="${IRLSPLIT:-0.685}"
IRLVR="${IRLVR:-0.445}"
IRLVG="${IRLVG:-0.0}"
IRLVB="${IRLVB:-1.0}"
IRLENDR="${IRLENDR:-0.75}"
IRLENDG="${IRLENDG:-0.18}"
IRLENDB="${IRLENDB:-0.87}"
RLO="${RLO:-1}"
RHI="${RHI:-1}"
GLO="${GLO:-1}"
GHI="${GHI:-1}"
BLO="${BLO:-1}"
BHI="${BHI:-1}"
exec env \
  IR3=1 \
  IRRATIO="$IRRATIO" IRT="$IRRATIO" \
  IRS="$IRS" IRL="$IRL" IRSH="$IRSH" IRGM="$IRGM" \
  IRSPLIT="$IRSPLIT" IRSENDR="$IRSENDR" IRSENDG="$IRSENDG" IRSENDB="$IRSENDB" \
  IRLSPLIT="$IRLSPLIT" IRLVR="$IRLVR" IRLVG="$IRLVG" IRLVB="$IRLVB" \
  IRLENDR="$IRLENDR" IRLENDG="$IRLENDG" IRLENDB="$IRLENDB" \
  RR=1 RG=0 RB=0 \
  GR=0 GG=1 GB=0 \
  BR=0 BG=0 BB=1 \
  RLO="$RLO" RHI="$RHI" \
  GLO="$GLO" GHI="$GHI" \
  BLO="$BLO" BHI="$BHI" \
  NA=1 \
  "$JPEG_BIN" "$@"
